### ISSUE TITLE
Fehler beim Clear Command (One Time Failure?)

### ISSUE THREAD

**Issue by 1887jonas** [nevar-bot/nevar#29]
```js
TypeError: Cannot read properties of undefined (reading 'author')
    at ClearCommand.clearMessages (file:///home/Nevar/nevar/src/commands/moderation/clear.ts:65:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ClearCommand.dispatch (file:///home/Nevar/nevar/src/commands/moderation/clear.ts:48:3)```

**Comment by 1887jonas** [comment]
konnte nicht mehr reproduziert werden
