### ISSUE TITLE
Clearcommand User Filter

### ISSUE THREAD

**Issue by 1887jonas** [nevar-bot/nevar#39]
Nachrichten von bestimmten Usern zu löschen funktioniert nur, wenn die letzten Nachrichten im Channel von diesem User sind, ansonsten:
```
TypeError: Cannot read properties of undefined (reading 'author')
    at ClearCommand.clearMessages (file:///home/Nevar/nevar/src/commands/moderation/clear.ts:65:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ClearCommand.dispatch (file:///home/Nevar/nevar/src/commands/moderation/clear.ts:48:3)
```

**Comment by 1887jonas** [comment]
nicht mehr nachstellbar
