### ISSUE TITLE
AI Chat funktioniert nicht wenn Kontext zu lang

### ISSUE THREAD

**Issue by 1887jonas** [nevar-bot/nevar#5]
evtl kürzen sobald der Kontext Array eine bestimmte Länge erreicht hat

**Comment by 1887jonas** [comment]
Error:
```
Error: 400 This model's maximum context length is 16385 tokens. However, your messages resulted in 17955 tokens. Please reduce the length of the messages.
    at Function.generate (/home/Nevar/nevar/node_modules/openai/src/error.ts:56:14)
    at OpenAI.makeStatusError (/home/Nevar/nevar/node_modules/openai/src/core.ts:348:21)
    at OpenAI.makeRequest (/home/Nevar/nevar/node_modules/openai/src/core.ts:406:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at _class.dispatch (/home/Nevar/nevar/src/events/message/MessageCreate.ts:268:61)
```
